
services:

  mysql-devjob:
    image: mysql:8.0.41-debian
    container_name: mysql-adam-store
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: adamstore
    volumes:
      - adam_store_data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3308:3306'
    networks:
      - adamstore_backend
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456" ]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s


  redis:
    image: redis:6.2-alpine
    container_name: redis-adam-store
    hostname: redis-adam-store
    restart: unless-stopped
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=123456
      - REDIS_DISABLE_COMMANDS=FLUSHDB;FLUSHALL
    command: redis-server --requirepass 123456
    networks:
      - adamstore_backend


  spring-adam-store:
    container_name: spring-adam-store
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8080'
    networks:
      - adamstore_backend
    depends_on:
      mysql-devjob:
        condition: service_healthy

networks:
  adamstore_backend:
    driver: bridge

volumes:
  adam_store_data:
    driver: local
